"""Initial migration

Revision ID: 11646a4a9fa7
Revises: 
Create Date: 2025-07-16 20:11:50.747873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11646a4a9fa7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
